language: node_js
node_js:
    - 12.16.1
cache: npm
install:
    - npm ci
script:
    - npm run build

deploy:
    provider: vercel
    skip-cleanup: true
    vercel-token: $VERCEL_TOKEN
    local_dir: dist
    on:
        branch: master
