language: node_js
node_js:
    - 12.16.1
cache: npm
install:
    - yarn
script:
    - yarn build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    target_branch: gh-pages
    on:
        branch: master
